import { 
  // Assuming the client is named GameLiftStreamsClient in the new package
  GameLiftStreamsClient, 
  StartStreamSessionCommand, 
  GetStreamSessionCommand 
  // We might need other specific types/commands from this package
} from '@aws-sdk/client-gameliftstreams'; // Hypothesized package name
import { v4 as uuidv4 } from 'uuid';

// Initialize GameLift Streams client (using the hypothesized client)
const gameliftStreamsClient = new GameLiftStreamsClient({
  region: import.meta.env.VITE_AWS_REGION,
  credentials: {
    accessKeyId: import.meta.env.VITE_AWS_ACCESS_KEY_ID,
    secretAccessKey: import.meta.env.VITE_AWS_SECRET_ACCESS_KEY,
  },
});

// Interface reflecting the START command's output needed by client
export interface InitialStreamingSession {
  streamingSessionArn: string; 
  status: string; 
  signalResponse?: string; // Crucial for the client WebSDK
  webSdkProtocolUrl?: string; // Potentially useful for client SDK
  // Add other potentially useful fields from StartStreamSession response if needed
}

/**
 * Initiates a GameLift stream session using an offer (SignalRequest) from the client.
 * Returns session details including the answer (SignalResponse) needed by the client.
 */
export const initiateGameLiftSession = async (
  submissionId: string, // Passed as UserId for tracking
  clientSignalRequest: string // The offer generated by the client WebSDK
): Promise<InitialStreamingSession> => {
  try {
    const streamGroupId = import.meta.env.VITE_GAMELIFT_STREAM_GROUP_ID;
    const applicationId = import.meta.env.VITE_GAMELIFT_APPLICATION_ID;
    const protocol = import.meta.env.VITE_GAMELIFT_STREAM_PROTOCOL || 'RTMP'; // Protocol MUST match client SDK expectation
    
    console.log("[GameLift] Starting session with:", {
      streamGroupId,
      applicationId,
      protocol,
      submissionId,
      signalRequestLength: clientSignalRequest?.length
    });

    if (!streamGroupId || !applicationId) {
      throw new Error('Missing required GameLift Streams environment variables (Stream Group ID, Application ID).');
    }
    if (!clientSignalRequest) {
       throw new Error('Client SignalRequest (offer) is required.');
    }

    const startCommand = new StartStreamSessionCommand({
      Identifier: streamGroupId,
      ApplicationIdentifier: applicationId,
      Protocol: protocol,
      SignalRequest: clientSignalRequest, // Use the offer from the client
      UserId: submissionId,
      // Add other optional parameters like SessionLengthSeconds if needed
    });

    console.log("[GameLift] Sending StartStreamSession command...");
    const response = await gameliftStreamsClient.send(startCommand);
    console.log("[GameLift] StartStreamSession response:", {
      arn: response?.Arn,
      status: response?.Status,
      hasSignalResponse: !!response?.SignalResponse,
      signalResponseLength: response?.SignalResponse?.length,
      webSdkUrl: response?.WebSdkProtocolUrl
    });

    // Access top-level properties based on documentation
    const actualSessionArn = response?.Arn;
    const initialStatus = response?.Status || 'UNKNOWN';
    const signalResponse = response?.SignalResponse; // Get the crucial SignalResponse (answer)
    const webSdkUrl = response?.WebSdkProtocolUrl; 

    if (!actualSessionArn) {
      console.error("[GameLift] StartStreamSession response missing Arn:", response);
      throw new Error('Failed to start streaming session - Could not determine Session ARN from response.');
    }
     if (!signalResponse) {
      // This is critical for the client to connect
      console.error("[GameLift] StartStreamSession response missing SignalResponse:", response);
      throw new Error('Failed to start streaming session - Server did not provide SignalResponse.');
    }

    console.log(`[GameLift] Stream session initiated successfully: ${actualSessionArn}, Status: ${initialStatus}`);
    return {
      streamingSessionArn: actualSessionArn,
      status: initialStatus,
      signalResponse: signalResponse,
      webSdkProtocolUrl: webSdkUrl,
    };
  } catch (error) {
    console.error('[GameLift] Error initiating stream session:', error);
    if (error instanceof Error) {
      console.error(`[GameLift] AWS Error Code: ${(error as any).name}`);
      console.error(`[GameLift] AWS Error Message: ${(error as any).message}`);
      if ((error as any).$metadata) {
        console.error(`[GameLift] AWS Error Metadata:`, (error as any).$metadata);
      }
    }
    throw error; // Re-throw to be handled by the caller
  }
};

// Removed checkStreamingSessionStatus, waitForStreamingSession, deployToGameLiftStreams
// as the connection and waiting logic is now primarily client-driven via the WebSDK. 